_target_: dem.energies.lennardjones_energy.LennardJonesEnergy

dimensionality: 165
n_particles: 55
data_path: "data/test_split_LJ55-1000-part1.npy"
data_path_train: "data/train_split_LJ55-1000-part1.npy"
data_path_val: "data/val_split_LJ55-1000-part1.npy"

device: ${trainer.accelerator}

plot_samples_epoch_period: 1

data_normalization_factor: 1.0

is_molecule: True
